-- Migration 044: Excel Import Tools — short links, balance RPC, SMS default, AI usage tracking
-- ================================================================================

-- 1. Change default sms_balance to 10 (was 50 from migration 031)
ALTER TABLE merchants ALTER COLUMN sms_balance SET DEFAULT 10;

-- 2. Add nickname column to merchant_customers for per-merchant display names
ALTER TABLE merchant_customers ADD COLUMN IF NOT EXISTS nickname TEXT;

-- 3. Short links table for SMS URL shortening
CREATE TABLE IF NOT EXISTS short_links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code VARCHAR(10) UNIQUE NOT NULL,
  destination_url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE short_links ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public_select" ON short_links FOR SELECT USING (true);
CREATE POLICY "service_role_insert" ON short_links FOR INSERT TO service_role WITH CHECK (true);

-- 4. AI usage tracking table for merchant bill parse quota
CREATE TABLE IF NOT EXISTS merchant_ai_usage (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  merchant_id UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
  model_name TEXT NOT NULL DEFAULT 'gemini-2.5-flash',
  input_tokens INTEGER NOT NULL DEFAULT 0,
  output_tokens INTEGER NOT NULL DEFAULT 0,
  parse_count INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(merchant_id, created_at::date, model_name)
);

ALTER TABLE merchant_ai_usage ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_role_all" ON merchant_ai_usage FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 5. Bulk SMS balance decrement RPC
CREATE OR REPLACE FUNCTION decrement_sms_balance_bulk(p_merchant_id UUID, p_amount INTEGER)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  UPDATE merchants
  SET sms_balance = GREATEST(COALESCE(sms_balance, 0) - p_amount, 0)
  WHERE id = p_merchant_id;
END;
$$;

-- 6. RPC: Get customer balance including pending Opening Balance entries
CREATE OR REPLACE FUNCTION get_customer_balance(p_merchant_id UUID, p_customer_id UUID)
RETURNS NUMERIC LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_balance NUMERIC;
BEGIN
  SELECT COALESCE(SUM(
    CASE WHEN type = 'debit' THEN amount ELSE -amount END
  ), 0) INTO v_balance
  FROM credit_logs
  WHERE merchant_id = p_merchant_id
    AND customer_id = p_customer_id
    AND (status = 'approved' OR (status = 'pending' AND description LIKE 'Opening Balance%'))
    AND type != 'cash';
  RETURN v_balance;
END;
$$;

-- 7. RPC: Bulk import customers with opening balance in a single transaction
-- Payload format: JSON array of objects with merchant_id, phone, name, amount, short_code (nullable)
-- For rows where sendSms is true, short_code is pre-generated by the TypeScript server action
-- and the short_link is inserted atomically after the credit_log insertion.
CREATE OR REPLACE FUNCTION import_customers(p_payload JSONB)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  item JSONB;
  v_customer_id UUID;
  v_log_id UUID;
  v_results JSONB[] := '{}';
BEGIN
  FOR item IN SELECT * FROM jsonb_array_elements(p_payload)
  LOOP
    -- Upsert customer by phone
    INSERT INTO customers (phone, name)
    VALUES (item->>'phone', item->>'name')
    ON CONFLICT (phone) DO UPDATE SET name = COALESCE(customers.name, EXCLUDED.name)
    RETURNING id INTO v_customer_id;

    -- Upsert merchant_customer junction with nickname
    INSERT INTO merchant_customers (merchant_id, customer_id, nickname)
    VALUES ((item->>'merchant_id')::UUID, v_customer_id, item->>'name')
    ON CONFLICT (merchant_id, customer_id) DO UPDATE SET nickname = EXCLUDED.nickname;

    -- Insert credit_log with status = 'pending', description = 'Opening Balance (Excel Imported)'
    INSERT INTO credit_logs (merchant_id, customer_id, amount, type, status, description, initiated_by)
    VALUES (
      (item->>'merchant_id')::UUID,
      v_customer_id,
      (item->>'amount')::NUMERIC,
      'debit',
      'pending',
      'Opening Balance (Excel Imported)',
      'merchant'
    )
    RETURNING id INTO v_log_id;

    -- If a short_code was provided, insert the short_link atomically
    IF item ? 'short_code' AND item->>'short_code' IS NOT NULL AND item->>'short_code' != '' THEN
      INSERT INTO short_links (code, destination_url)
      VALUES (item->>'short_code', '/customer/verify?log_id=' || v_log_id::TEXT);
    END IF;

    v_results := array_append(v_results, jsonb_build_object(
      'phone', item->>'phone',
      'customer_id', v_customer_id,
      'log_id', v_log_id
    ));
  END LOOP;

  RETURN jsonb_build_array(variadic v_results);
END;
$$;
